version: 2.1
orbs:
  codecov: codecov/codecov@4.0.1
jobs:
  build-and-test:
    docker:
      - image: cimg/openjdk:11.0

    steps:
      - checkout
      - run:
          name: Build
          command: mvn -B -DskipTests clean package
      - run:
          name: Test
          command: mvn test
      - run:
          name: Upload Codecov
          command: bash <(curl -s https://codecov.io/bash)
      - run:
          name: Generate Checkstyle and Javadoc
          command: mvn site

  docs-deploy:
    docker:
      - image: node:8.10.0
    steps:
      - checkout
      - attach_workspace:
          at: docs/
      - run:
          name: Install and configure dependencies
          command: |
            npm install -g --silent gh-pages@2.0.1
            git config user.email "walid.medouaz@alumni.univ-avignon.fr"
            git config user.name "WalidMedouaz"
      - run:
          name: Deploy docs to gh-pages branch
          command: gh-pages --dist docs/apidocs/


workflows:
  sample:
    jobs:
      - build-and-test:
          filters:
            branches:
              only: master
      - docs-deploy:
          requires:
            - build-and-test
          filters:
            branches:
              only: master