version: 2.1

jobs:
  build-and-test:
    docker:
      - image: cimg/openjdk:11

    steps:
      - checkout
      - run:
          name: Build
          command: mvn -B -DskipTests clean package
      - run:
          name: Test
          command: mvn test
workflows:
  sample:
    jobs:
      - build-and-test:
          filters:
            branches:
              only: master
